version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "6000:5432"
  server:
   build:
     context: ./server
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   environment:
     - DB_PROTOCOL=postgresql
     - DB_USER=root
     - DB_PASSWORD=secert
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_NAME=panda_bank
     - DB_SSL=sslmode=disable
   depends_on:
     - postgres
   command: go run main.go
  client:
     build:
      context: ./client
      dockerfile: Dockerfile
     ports:
      - "3000:3000"
     environment:
     - HOST=server
     depends_on:
     - server
     command: npm run dev
