apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          # image: <aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/<repository_name> 
          ports: 
            - containerPort: 5000
          env: 
           -  name: DB_USER
              value: admin
           -  name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: pgpassword  
                 key: PGPASSWORD
           -  name: DB_HOST
              value: postgres-cluster-ip-service
           - name: DB_PORT
             value: "5432"
           - name : DB_NAME
             value: panda_bank
           - name : DB_SSL
             value: sslmode=disable # chnage when ssl is set up 
           - DB_PROTOCOL=postgresql

