import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Menu } from '../interfeace'
import { useState } from 'react'
import Link from 'next/link'

const Home: NextPage = () => {


  const [burger,setBurger] = useState(false)




  const menuList: Menu []=[
       {menuName:"About", Navigate:"/About"},
       {menuName: "News", Navigate:"/Shop"},
       {menuName: "Help", Navigate:"/Collection"},
       {menuName: "Features", Navigate:'/desingers'},
       {menuName: "Careers", Navigate:'/Orders'},
       ]
  

       

  
  return (
    <div className='relative scroll-smooth'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='fixed z-50 flex w-screen h-16 px-4 bg-black lg:px-20'>
          <Image src={"/panda_logo.svg"} width={"40px"} height={"40px"}/>
          <h1 className='self-center w-4 ml-1 text-white'>PANDA BANK</h1>

          <div className='absolute self-center hidden space-x-10 right-80 md:flex'>

          {menuList.map((menu,i)=>(
     
     <div className='flex flex-col group active:scale-90' key={i}>
      <Link href={menu.Navigate}>
          <h1 className='text-white duration-300 cursor-pointer group-hover:opacity-50 group-hover:-translate-y-1'>{menu.menuName}</h1>
          </Link>
          
          <div className='w-10 h-0.5 bg-white self-center scale-0 group-hover:scale-100 duration-500'></div> 
     </div>))}

          </div>

          <Link href={"/signup"}><button className='absolute self-center hidden h-8 text-black bg-white rounded-full w-28 right-12 md:right-40 md:mr-2 md:block'>Get started</button></Link>
          

          <Link href={"/login"}><button className='absolute self-center hidden h-8 text-white border rounded-full w-28 right-12 md:block '>Log in</button></Link>
          
          <div className='space-y-1.5 mt-1 group cursor-pointer self-center absolute right-0 mr-4 md:hidden' onClick={()=>setBurger(!burger)}>
     <div className={`bg-white w-5 h-0.5 rounded-lg ${burger && 'rotate-45 translate-y-2'} duration-500`}></div>
     <div className={`bg-white w-5 h-0.5 rounded-lg ${burger && 'scale-0'} duration-500`}></div>
     <div className={`bg-white w-5 h-0.5 rounded-lg ${burger && '-rotate-45 -translate-y-2'} duration-500`}></div>
     </div>
     </div>


     <div className={` w-screen h-[70rem] pt-20 scr bg-black absolute right-0 translate-x-[100vw] ${burger && 'translate-x-0'} duration-500 flex flex-col space-y-40`} >
     <div className='flex flex-col space-y-10'>
          {menuList.map((e,i)=>(
                <Link href={e.Navigate} key={i}>
               <button className='flex items-center justify-between w-screen h-10 px-4 border-b border-white/10 hover:border-white/5 group'>
                    <p className='text-2xl text-white group-hover:text-white/50'>{e.menuName}</p>
  
                    
               </button>
          </Link>

          ))}</div>
          <div className='flex flex-col w-screen mt-40 space-y-10'>
              <Link href={"/signup"}><button className='self-center h-12 text-black bg-white rounded-full w-80 right-12 md:right-40 md:mr-2 md:block'>Get started</button></Link>
          
          <Link href={"/login"}><button className='self-center h-12 text-white border rounded-full w-80 right-12 md:block'>Log in </button></Link>
          
          </div>
          
     </div>








     <div className='bg-hero-panda h-[70rem] bg-no-repeat bg-cover px-6 pt-8 md:pt-32  lg:px-20  md:bg-hero-pand-md md:h-[60rem] flex flex-col bg-fixed  '>

          <h3 className='mt-20 text-white '>PANDA DIGITAL BANKING</h3>

          <h1 className='text-6xl font-bold text-white'>Banking with a difference</h1>
          
          <p className='mt-2 text-xs text-white'>No branches, no problem. Get more from your money with Panda’s online bank accounts.</p>

            <div className={`flex mt-2 space-x-2 ${burger && "hidden"} `} ><Image src={"/Check.svg"} width={"20px"} height={"20px"} alt="check"/> <p className='text-white'>Fully regulated UK bank accounts</p></div>
            <div className={`flex mt-2 space-x-2 ${burger && "hidden"} `} ><Image src={"/Check.svg"} width={"20px"} height={"20px"} alt="check"/> <p className='text-white'>24/7 Customer support</p></div>
            <div className={`flex mt-2 space-x-2 ${burger && "hidden"} `} ><Image src={"/Check.svg"} width={"20px"} height={"20px"} alt="check"/> <p className='text-white'>Create an account in mintues</p></div>

          <button className='w-48 h-16 mt-4 text-black bg-white rounded-full'>Get started</button>
          
         <div className='bg-mobile-app w-80 h-[48rem] bg-cover bg-no-repeat self-center -mt-16 md:self-end md:-mt-64 md:mr-72 '></div>
     </div>




<div className={`${burger && 'hidden'}`}>


<div className='flex flex-col py-20'>
     <h2 className='w-96 self-center text-2xl md:w-[48rem] md:text-4xl'>With millions of accounts across the UK, someone joins Panda every 38 seconds *</h2>

     <div className='grid grid-cols-2 gap-10 px-20 mt-10 md:flex md:self-center '>
          <Image src={"/Bithish_Bank.svg"} width={"100px"} height={"100px"}/>
          <Image src={"/which.svg"} width={"100px"} height={"100px"}/>
          <Image src={"/protected.svg"} width={"100px"} height={"100px"}/>
          <Image src={"/trustpilot.svg"} width={"100px"} height={"100px"}/>
          <div className='hidden md:block'>  <Image  src={"/BBB-logo 1.svg"} width={"150px"} height={"150px"}/></div>
          <div className='col-span-2 md:hidden'>
          <Image src={"/BBB-logo 1.svg"} width={"400px"} height={"120px"}/>
          </div>
     </div>
     <p className='self-center mx-4 mt-10 text-sm font-light'>*This statistic was formed by calculating the number of accounts added in a 12 month period divided by the number of hours in a 12 month period.</p>


</div>


     


     <div className='px-4 mt-20 md:flex lg:px-20 xl:px-40 md:pb-10'>
          
          <div className='md:flex md:flex-col md:-mt-10'>
          <p className='text-2xl font-medium md:w-80'>Bringing banking without boundary</p>


          <div className='-mt-20'> <Image src={"/£0.svg"} height={"300px"} width={"300px"}/>
          <p className='text-lg font-medium -mt-28'>No monthly fees.</p>
          <p className='font-light'>Whether you’re personal or business.</p>
          </div>


          <div className='mt-20'> <Image src={"/phone_card.svg"} height={"100px"} width={"100px"}/>
          <p className='text-lg font-medium '>100% digital signup.</p>
          <p className='font-light'>Apply in minutes from your phone.</p>
          </div>

          </div>

          <div className='md:flex md:flex-col md:-mt-10'>

          <div className='mt-20'> <p className='text-6xl font-bold'>24/7</p>
          <p className='mt-4 text-lg font-medium '>24/7 UK customer support.</p>
          <p className='font-light'>Chat to real humans, any time.</p>
          </div>


          <div className='-mt-1'> <Image src={"/FSCS_lock.svg"} height={"200px"} width={"200px"}/>
          <p className='-mt-12 text-lg font-medium '>A fully-regulated UK bank account.</p>
          <p className='font-light'>Your money’s covered by the Financial Services Compensation Scheme.</p>
          </div>

          <div className='flex flex-col w-40 group'>
          <button className='w-40 py-3 mt-10 text-white duration-500 bg-black rounded-full hover:-translate-y-4'>Get started</button>
          <div className='h-0.5 bg-black  w-20 self-center scale-0 group-hover:scale-100 group-hover:-translate-y-1  duration-500'></div>

          </div>

          </div>
          <div className='mt-10 xl:ml-40 md:mt-2'>
               <Image src={"/Customer_care.svg"} width={"1000px"} height={"1000px"}/>
          </div>
     </div>

     <div className='w-screen px-4 py-10 bg-slate-100/70 md:flex lg:px-10 2xl:px-40 md:justify-between '>

     <div className='flex-wrap md:flex md:flex-col 2xl:mt-64 md:mt-30 '>
          <p className='text-xl font-bold'>Independent service quality survey results</p>

          <p className='font-light mt-4 md:w-[48rem]'>An independent survey asked customers if they would recommend their <br className='hidden lg:block'/> banking provider to friends and family. See Panda’s results for <br className='hidden lg:block'/><a className="underline decoration-green-600 hover:bg-green-600/50">business accounts</a> and <a className='underline decoration-green-600 hover:bg-green-600/50'>personal accounts</a>.</p>
        

        <p className="mt-4 text-[#05A89D] text-3xl">Overall service quality</p>
        <p className="mt-4 font-light md:w-[48rem]" >We asked customers how likely they would recommed thier personal <br className='hidden lg:block'/> current account provider to thier friends and family </p>

      
     </div>
     <Image src={"/panda_Compare.svg"} width={"1000px"} height={"1000px"}/>
     </div>





     <div className="flex flex-col w-screen overflow-hidden md:bg-stone-table h-[48rem] justify-center relative items-center bg-cover bg-no-repeat" > 
    

      <p className='mb-10 text-lg font-bold'>Everything you get with Panda</p>
   
     <div className="grid grid-cols-3 gap-2" >
      <div className='flex flex-col'>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      </div>
      <div className='flex flex-col'>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      </div>
      <div className='flex flex-col'>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      <div className='flex mt-2 space-x-2 '><Image src={"/Check1.svg"} width={"20px"} height={"20px"} alt="check"/> <p className="text-xs" >Fully regulated UK bank accounts</p></div>
      </div>
     </div>
     
      
     <div className='absolute hidden -top-40 2xl:right-10 xl:block -right-28'> <Image src={"/white_card.svg"} width={"600px"} height={"600px"}/></div>
    
     <div className='absolute hidden -bottom-40 2xl:left-10 xl:block -left-28'> <Image src={"/black_card.svg"} width={"600px"} height={"600px"}/></div>

      
      

     
     </div>
     
</div>
     
    </div>
  )
}

export default Home
