// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	Owner         string    `json:"owner"`
	CardNumber    int64     `json:"card_number"`
	AccountNumber int32     `json:"account_number"`
	SortCode      string    `json:"sort_code"`
	IssuedDate    string    `json:"issued_date"`
	ExpireDate    string    `json:"expire_date"`
	Balance       int64     `json:"balance"`
	CreatedAt     time.Time `json:"created_at"`
}

type Entry struct {
	ID             int64     `json:"id"`
	Amount         int64     `json:"amount"`
	EntryFirstName string    `json:"entry_first_name"`
	EntryLastName  string    `json:"entry_last_name"`
	AccountNumber  int32     `json:"account_number"`
	CreatedAt      time.Time `json:"created_at"`
}

type Payee struct {
	ID             int64  `json:"id"`
	PayeeFirstName string `json:"payee_first_name"`
	PayeeLastName  string `json:"payee_last_name"`
	OwnerEmail     string `json:"owner_email"`
	AccountNumber  int32  `json:"account_number"`
	SortCode       string `json:"sort_code"`
}

type Transfer struct {
	ID           int64     `json:"id"`
	FromSortCode string    `json:"from_sort_code"`
	FromAccount  int32     `json:"from_account"`
	ToFirstName  string    `json:"to_first_name"`
	ToLastName   string    `json:"to_last_name"`
	ToSortCode   string    `json:"to_sort_code"`
	ToAccount    int32     `json:"to_account"`
	Amount       int64     `json:"amount"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Password  string `json:"password"`
	Email     string `json:"email"`
}
