// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreatUser(ctx context.Context, arg CreatUserParams) (User, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error)
	Createtransaction(ctx context.Context, arg CreatetransactionParams) (Transfer, error)
	DeteUser(ctx context.Context, arg DeteUserParams) error
	GetAccount(ctx context.Context, accountNumber int32) (Account, error)
	GetAccountByEmail(ctx context.Context, owner string) (Account, error)
	GetAccountForUpdate(ctx context.Context, accountNumber int32) (Account, error)
	GetEntry(ctx context.Context, accountNumber int32) (Entry, error)
	GetPayee(ctx context.Context, ownerEmail string) ([]GetPayeeRow, error)
	GetPayeeAccount(ctx context.Context, accountNumber int32) (GetPayeeAccountRow, error)
	GetPayeeFavourite(ctx context.Context, ownerEmail string) ([]GetPayeeFavouriteRow, error)
	GetUser(ctx context.Context, email string) (User, error)
	Gettransaction(ctx context.Context, id int64) (Transfer, error)
	ListEntries(ctx context.Context, accountNumber int32) ([]Entry, error)
	Listtransaction(ctx context.Context, arg ListtransactionParams) ([]Transfer, error)
}

var _ Querier = (*Queries)(nil)
